### ISSUE TITLE
[BUG]: UB in annotated_ptr

### ISSUE THREAD

**Issue by Artem-B** [NVIDIA/cccl#2942]
### Is this a duplicate?

- [x] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this bug and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Type of Bug

Runtime Error

### Component

libcu++

### Describe the bug

There's a potential UB path, triggered by the `annotated_ptr_constructors.pass.cpp` https://github.com/NVIDIA/cccl/blob/83d180f487ac85c3985d39835d665ae676ba49b0/libcudacxx/test/libcudacxx/cuda/annotated_ptr/annotated_ptr_constructors.pass.cpp#L36

`def` is default-initialized and ands up with `def.__repr` == `nullptr` due to https://github.com/NVIDIA/cccl/blob/83d180f487ac85c3985d39835d665ae676ba49b0/libcudacxx/include/cuda/annotated_ptr#L317

The constructor invoked by the test ends up eventually dereferencing `__repr` here: https://github.com/NVIDIA/cccl/blob/83d180f487ac85c3985d39835d665ae676ba49b0/libcudacxx/include/cuda/annotated_ptr#L395

Full stack trace:
```
#4  0x0000555558f3f40f in __ubsan_handle_type_mismatch_v1_abort () at third_party/llvm/llvm-project/compiler-rt/lib/ubsan/ubsan_handlers.cpp:148
#5  0x0000555558f45ba9 in cuda::__4::annotated_ptr<int, cuda::__4::access_property::global>::operator* (this=0x7fffffffd2f8) at third_party/gpus/cuda/include/cuda/annotated_ptr:341
#6  0x0000555558f45a3e in cuda::__4::annotated_ptr<int, cuda::__4::access_property::normal>::get (this=0x7fffffffd408) at third_party/gpus/cuda/include/cuda/annotated_ptr:395
#7  0x0000555558f454bc in cuda::__4::annotated_ptr<int const, cuda::__4::access_property::normal>::annotated_ptr<int, cuda::__4::access_property::normal> (this=0x7fffffffd3e0, __other=...)
    at third_party/gpus/cuda/include/cuda/annotated_ptr:408
#8  0x0000555558f44e6f in test_ctor<int, cuda::__4::access_property::normal> () at third_party/gpus/cccl/v2_6_0/libcudacxx/test/libcudacxx/cuda/annotated_ptr/annotated_ptr_constructors.pass.cpp:36
#9  0x0000555558f449ed in test_global_ctor<int, cuda::__4::access_property::normal> () at third_party/gpus/cccl/v2_6_0/libcudacxx/test/libcudacxx/cuda/annotated_ptr/annotated_ptr_constructors.pass.cpp:62
#10 0x0000555558f44849 in test_global_ctors () at third_party/gpus/cccl/v2_6_0/libcudacxx/test/libcudacxx/cuda/annotated_ptr/annotated_ptr_constructors.pass.cpp:75
#11 0x0000555558f446c4 in fake_main (argc=1, argv=0x7fffffffd768) at third_party/gpus/cccl/v2_6_0/libcudacxx/test/libcudacxx/cuda/annotated_ptr/annotated_ptr_constructors.pass.cpp:85
#12 0x0000555558f44032 in main (argc=1, argv=0x7fffffffd768) at third_party/gpus/cccl/v2_6_0/libcudacxx/test/libcudacxx/force_include.h:78
```

Adding a check for `nullptr` in `get()` appears to avoid the problem, but I'm not sure if that's the right fix, or just hides the problem.

```
@@ -391,6 +391,8 @@ public:

   _CCCL_HOST_DEVICE pointer get() const noexcept
   {
+    if (__repr == nullptr)
+      return nullptr;
     constexpr bool __is_shared = std::is_same<_Property, access_property::shared>::value;
     return __is_shared ? __repr : &(*annotated_ptr<value_type, access_property::global>(__repr));
   }
```

### How to Reproduce

Build and run `annotated_ptr_constructors.pass.cpp` with `clang -O0`, libc++ and ubsan with null checks enabled.
Observe the null pointer dereference report.

### Expected behavior

No `nullptr` dereference.

**Comment by Artem-B** [comment]
@miscco - FYI.
